server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: EurekaGateway
  cloud:
    gateway:
      routes:
        - id: MicroServiceUser
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: MicroServiceBoard
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/boards/**
        - id: MicroServiceCertification
          uri: lb://CERTIFICATION-SERVICE
          predicates:
            - Path=/certifications/**