server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: EurekaGateway
  cloud:
    gateway:
      routes:
        - id: MicroServiceUser
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: MicroServiceBoard
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/boards/**


rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1RihXy7eAmStotXwDMVKi4VYz6fVrnfKJ9ps1yk5KAWvoFvJaEyME/p9vqzcT+2wdCU7oIzDzB4jsyIrBvRHgsXf4o4kAA/o+Ks/t61fKIc1qLqyobxEKrpiq8LxeFwI2vEOzsj85tb8RrXcRVOnCDjIga/Wqv7iqz1CsLb7VEkhA6W5qdER5/7PLWylYk9w48D/FsumEanWVWkYikaKUIB8j87y9SJQtI1PWHzFN3elG0tiB9lQK4wMfYsDzPK9nougpboBRECFIKbnSe2+bGysKKGxvkVXE7qsrpg+UAmyZX1+ibXuWbNP6lYrXalyBUkUmI8XuTCqu778E1RuLwIDAQAB
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDVGKFfLt4CZK2i1fAMxUqLhVjPp9Wud8on2mzXKTkoBa+gW8loTIwT+n2+rNxP7bB0JTugjMPMHiOzIisG9EeCxd/ijiQAD+j4qz+3rV8ohzWourKhvEQqumKrwvF4XAja8Q7OyPzm1vxGtdxFU6cIOMiBr9aq/uKrPUKwtvtUSSEDpbmp0RHn/s8tbKViT3DjwP8Wy6YRqdZVaRiKRopQgHyPzvL1IlC0jU9YfMU3d6UbS2IH2VArjAx9iwPM8r2ei6ClugFEQIUgpudJ7b5sbKwoobG+RVcTuqyumD5QCbJlfX6Jte5Zs0/qVitdqXIFSRSYjxe5MKq7vvwTVG4vAgMBAAECggEAS8LJ/JEpFSi+Itp00dWCvz/VZ16ANdsY4Dpj38skKvp6ikSXwqEUXDX+ZsAGQ9R5m5FxNY9WPUep4ZIQQhSvJ+s5wc5PNkZxyZb4vFDDOCF6DlbyE1Zf1eEWG4LfXq855r01Sodigp+EaY9WlL8870tg3dqqM3kTFVZeU316tWf0DzEBUyWZoYQKwseSLMSasgCQ5ntygC0DWzx5TB94pk7DNrbV2VTDJjubTHdzbILpDqFH5hcGfoFKQlJgmcvTa638+dVZZM3ocQxcjSsAs238ANR6iNPkXk3mtWGsTlaB7nnmM8LaQggFOYUe/BGj91e97oq/g9wpuRSnFE+eYQKBgQD424Zw/vOWHmhsI6vUhhGe0kF5m14ij0/0A63JG+yTei9MZ5A7UGha9+ummTHiO7aKhPXgyukM1UxkEt9J1nu7x74qqjcti4tiTeVAczPDgKvVHOmWNJ3jOWcel0pCVdxe5o5PQYslPjvc7DF3PVN6wR0bib1W8Ul8UD0ekwk7/QKBgQDbNlmNy/hfGUqpGt4TOAT1BdDh1BFuSURxPK6lsgYO24JwCsboVilodBYP2X/jxmAMX/zru28izFc0tF2Nyug/xJepI/ZJyZdpxIIg6TCTnX7V6ohi8I4JhG0T905RPLpl2wIeea985BEDbz20a76bW/N8LNQlyjEhFwMdswZMmwKBgQCBbIpLEg1VMZNVSmf/K4rWcrsip68ZgjcuzQsA4Mj1GkKnFeVpM7RSO0YPavUKl8uj1uqZcm4qAnSsRzRhjm7jhkpcnhH8WeqvwZtNHZz6PF0hhNvnBo5msl/zBPPV9BmcMYQprAjV4bv4dc50GSzlVrHwtH4ITYzOXlyrHgVbcQKBgQC2k3XTG+cpja8ZWT9NUoMOcGGhNTevW2adyaTMbJGPHlRtbQxtxhWG4ejeGpDh7P9iTzAgRmQx329ifjbNOgpl0h9eyI0At95cQUcAkjfbOnnBQS2G+kPSuXEACCI6lxHIc7g4GbGHm4xwB96kvnhqfRM2gT/Qma6BmOEHg2vjsQKBgQDk4ZhA+K6oG6Bf0uar5D+lBGAPKV2MOdi2jfEFhssaak/0wMc5Xeg12ajVgK3hNktAk1TytgtOO5rztWusZRNjJTcbfMJr+NekAvF5+HtEkyPCM3MPro/1Y3CTuAx/eSRhZyodABfS5vx8phtH3ufn6I1kZD+ufCkYSxEhT+iz4Q==


jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  expiration: 604800000