server:
  port: 5003

spring:
  application:
    name: MicroServiceCertification
  datasource:
    url: jdbc:mariadb://localhost:3306/certificationservice
    username: admin123
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka