server:
  port: 5002

spring:
  application:
    name: MicroServiceBoard
  datasource:
    url: jdbc:mariadb://localhost:3306/boardservice
    username: admin123
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:  # src/main/resources/mappers/ 하위
  mapper-locations: classpath:/mappers/**/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  expiration: 604800000

